<?php

// +----------------------------------------------------------------------
// | FileName:   HomeController.class.php
// +----------------------------------------------------------------------
// | Dscription:   前台基类控制器
// +----------------------------------------------------------------------
// | Date:  2017/7/31 13:32
// +----------------------------------------------------------------------
// | Author: showkw <showkw@163.com>
// +----------------------------------------------------------------------

namespace  Home\Controller;

use Home\Controller\HomeController;
use THink\Controller;
use Home\Controller\ProductController;

class HelpController extends HomeController
{
	
	protected function _initialize()
	{
		parent::_initialize(); // TODO: Change the autogenerated stub
	}

    public function login()
    {
        $this->display();
    }
    public function find()
    {
        $this->display();
    }
    public function process()
    {
        $this->display();
    }
    public function question()
    {
        $this->display();
    }


}
