<?php

// +----------------------------------------------------------------------
// | FileName:   HomeController.class.php
// +----------------------------------------------------------------------
// | Dscription:   前台基类控制器
// +----------------------------------------------------------------------
// | Date:  2017/7/31 13:32
// +----------------------------------------------------------------------
// | Author: showkw <showkw@163.com>
// +----------------------------------------------------------------------


namespace  Home\Controller;

use Admin\Controller\MsgController;
use Home\Model\ErpModel;
use THink\Controller;
use Home\Controller\BasketController;
use Home\Controller\ProductController;
use Common\Controller\UploadController as Upload;
use Common\Controller\KdApiController as KdApi;
use think\Log;

class KnotorderController extends BasketController
{

	use Upload;

	protected function _initialize()
	{
		parent::_initialize(); // TODO: Change the autogenerated stub
		$url_path=I('path.');
		if(!in_array($url_path[1],['search','basketDetail','notify','alipay_notify','orderpaytest'])){
			!is_login() && redirect(U('Home/Account/login'));
		}
		$user_id = session( 'userId' );
		$userType = session('userType');
		if( $userType == 1 ){
			$key = 'ssid_'.$user_id;
			if(S($key)){
				$ssid = S($key);
				if( $this->ssid !== $ssid ){
					session(null);
					S($key,null);
					redirect(U('Home/Account/login', ['isRelogin'=>1]));
				}
			}
		}

		$companySons=(new OrderController())->companySons();//企业子账号信息
		if($companySons['error']==0){
		    $users=$companySons['data'];
		    $user_id=['in',$users];
        }

        //查询用户待付款订单条数
        $noPay_list = D( 'order' )->where( [ 'user_id' => $user_id, 'pay_status' => 0, 'order_status'=>['in',[0,1]] ] )->select();
        $noPayNum = count($noPay_list);
        $this->assign('noPayNum', $noPayNum);

        //查询待发货条数
        $noShip_list = D( 'order' )->where( [ 'user_id' => $user_id, 'ship_status' => 0, 'order_status'=>['in', [0,1,2]] ] )->select();
        $noShipNum = count($noShip_list);
        $this->assign('noShipNum', $noShipNum);

        //查询待收货条数
        $noDelivery_list = D( 'order' )->where( [ 'user_id' => $user_id,'order_status'=>['in', [0,1,2]], 'ship_status' =>['in', [2,3]]  ] )->select();
        $noDeliveryNum = count($noDelivery_list);
        $this->assign('noDeliveryNum', $noDeliveryNum);

        //查询待评价条数
        $noRelease_list = D( 'order' )->where( [ 'user_id' => $user_id, 'order_status' => 3, 'is_comment'=>1 ] )->select();
        $noReleaseNum = count($noRelease_list);
        $this->assign('noReleaseNum', $noReleaseNum);
	}


    /**
     * 申请返差额
     * @param
    $request=[
        'order_sn'=>'180424110275',
        'customer_account_type'=>'1',
        'customer_account'=>'123',
        'notify_mobile'=>'123',
        'account_name'=>'',
    ];
     * @return array
     */
	public function knotOrderRequest(){
	    if(IS_AJAX){
	        $request=I('post.');
	        $reslut=D('Admin/Order','Event')->updateOrder($request);
	        $return=['error'=>1,'msg'=>$reslut[0]['msg']];
	        if($reslut[0]['error']===0){
                $return=['error'=>0,'msg'=>'success'];
            }
            die(json_encode($return));
        }
    }










}