<?php

// +----------------------------------------------------------------------
// | FileName:   OrderController.class.bak.20170906.php
// +----------------------------------------------------------------------
// | Dscription:
// +----------------------------------------------------------------------
// | Date:  2017/8/22 15:14
// +----------------------------------------------------------------------
// | Author: showkw <showkw@163.com>
// +----------------------------------------------------------------------
namespace Admin\Controller;

use Common\Controller\BaseController;
use Common\Controller\Category;
use Common\Controller\TreeController;
use EES\System\Redis;
use http\Env\Response;

class AutoCompleteController extends AdminController
{

    protected function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
    }

    /**
     * @desc 业务员列表
     */
    public function customers(){
//        if(IS_AJAX){
            $request=I('get.');
            $where=[];
            $list=M('user','sys_')->field('')->where($where)->select();
            print_r($list);
//        }
    }



}