<?php

// +----------------------------------------------------------------------
// | FileName:   ProductController.php
// +----------------------------------------------------------------------
// | Dscription:
// +----------------------------------------------------------------------
// | Date:  2017/8/28 11:00
// +----------------------------------------------------------------------
// | Author: showkw <showkw@163.com>
// +----------------------------------------------------------------------
namespace  Admin\Controller;

class CategoryController extends AdminController
{
	public $_model;

	protected function _initialize()
	{
		parent::_initialize(); // TODO: Change the autogenerated stub
		$this->_model = D('product');
	}

    /**
     * @desc 产品分类列表
     *
     */
	public function categoryList(){
        $request=I('get.');
        $category=D('category')->productCategoryInfinite();
        if($category['error']!=0) die(json_encode($category));
        $categoryList=$category['data']['category'];
        $total=$category['data']['total'];

        if(isset($request['cate_id'])){
            $cateId_arr=D('category')->allLevelCategory($request['cate_id']);
            if($cateId_arr['error']==0){
                $cateId_arr['data']['list'][]=$request['cate_id'];
                $where['cate_id']=['in',$cateId_arr['data']['list']];
                $this->assign('cate_path',$cateId_arr['data']['path']);
            }
        }
        $this->assign('request',$request);
        $this->assign('categoryList',$categoryList);
        $this->assign('total',$total);
        $this->display();
    }

    /**
     * @desc 添加分类
     * @desc son  添加子类
     * @desc borther   向右边添加兄弟类
     * @desc 编辑分类
     *
     */
    public function addCategory(){
        if(IS_AJAX){
            $request=I('post.');
            if(!$request['id']||!$request['name']) die(json_encode(['error'=>1,'msg'=>'参数错误']));

            if(isset($request['action'])&&$request['action']=='edit'){//编辑分类名称
                $result=D('category')->categoryEdit($request);
                die(json_encode($result));
            }

            $type=($request['type']=='son')?'son':'brother';
            $result=D('category')->addCategory($request['id'],$request['name'],$type);
            die(json_encode($result));
        }
    }

    /**
     * @desc 分类删除分类
     *
     */
    public function deleteCategory(){
        if(IS_AJAX){
            $request=I('post.');
            $result=D('category')->deleteCategory($request['id']);
            die(json_encode($result));
        }
    }

    /**
     * @desc excel内容添加
     *
     */
    public function excelCategoryToDB(){
        $path='Uploads/productExcel/category_init.xlsx';
        $excel=new ExcelController();
        $read=$excel->excelRead($path);
        if($read['error']!=0) die(json_encode($read));
        $data=$read['data']['list'];
        array_shift($data);
        array_shift($data);
        $category=[];
        $level1=1;
        $level2=1;
        $level3=1;
        foreach($data as $k=>$v){
            if($v['A']&&$v['B']&&$v['C']){
                $level1+=1;
                $category[$level1]['name']=$v['A'];
                $category[$level1][$level2]['name']=$v['B'];
                $category[$level1][$level2][$level3++]['name']=$v['C'];
            }else if(!$v['A']&&$v['B']&&$v['C']){
                $level2+=1;
                $category[$level1][$level2]['name']=$v['B'];
                $category[$level1][$level2][$level3++]['name']=$v['C'];
            }else if(!$v['A']&&!$v['B']&&$v['C']){
                $level3+=1;
                $category[$level1][$level2][$level3]['name']=$v['C'];
            }
        }
//        print_r($category);
        $type='son';
        $id=1;
        foreach($category as $k=>$v){
            $result=D('category')->addCategory($id,$v['name'],$type);
            $id2=$result['id'];
            foreach($v as $k2=>$v2){
                if($k2!='name'){
                    $result2=D('category')->addCategory($id2,$v2['name'],$type);
                      $id3=$result2['id'];
                        foreach($v2 as $k3=>$v3){
                            if($k3!='name'){
                                $result3=D('category')->addCategory($id3,$v3['name'],$type);
                            }
                        }
                }
            }
        }
    }




}