<?php

// +----------------------------------------------------------------------
// | FileName:   RleaseController.class.php
// +----------------------------------------------------------------------
// | Dscription:
// +----------------------------------------------------------------------
// | Date:  2017/8/31 13:43
// +----------------------------------------------------------------------
// | Author: showkw <showkw@163.com>
// +----------------------------------------------------------------------
namespace  Admin\Controller;

use Admin\Controller\AdminController;

class ReleaseController extends AdminController
{
	protected function _initialize()
	{
		parent::_initialize(); // TODO: Change the autogenerated stub
	}
	
	/**
	 * @desc 列表首页页面
	 */
	public function index()
	{
		$this->display();
	}
	
	public function add(  )
	{
		//批量测试数据
		//for ( $i=0; $i<40; $i++ ){
		//	$data = [
		//		'link_name'=> chr(rand(65, 90))."先生",
		//		'link_mobile'=>rand(130,176).rand(00000000,99999999),
		//		'release_name'  =>chr(rand(65, 90))."产品",
		//		'brand_name'    =>chr(rand(65, 90))."品牌",
		//		'price'         =>rand(0.001, 0.1),
		//		'number'        =>rand(0, 50000),
		//		'delivery_time' =>rand(1,3).'-'.rand(3,5).'天',
		//		'end_time'      =>strtotime('+'.rand(3,5).' day'),
		//	];
		//	M('release')->add($data);
		//}

	}
	
	/**
	 * @desc 列表数据接口
	 *
	 */
	public function getList()
	{
		$res = D('release')->select();
		foreach( $res as $k=>$v ){
			if( empty($v['end_time']) ){
				$res[$k]['end_time'] = '未填写';
			}else{
				$res[$k]['end_time'] = date('Y-m-d H:i:s', $v['end_time']);
			}
			if( empty($v['link_name']) ){
				$res[$k]['link_name'] = '未填写';
			}
			if( empty($v['link_mobile']) ){
				$res[$k]['link_mobile'] = '未填写';
			}

		}
		$this->ajaxReturn($res, 'json');
	}

	/**
	 * @desc 修改状态 处理需求
	 */
	public function changeStatus(  )
	{
		$id = I('id');
		empty($id) && $this->ajaxReturnStatus(1000, 'id数据为空');
		if( is_array($id) ){
			$re = D('release')->where(['id'=>['in', $id]])->setField('handle_status', 1);
		}else{
			$re = D('release')->where(['id'=>$id])->setField('handle_status', 1);
		}
		if ( $re !== false ) {
			$this->ajaxReturnStatus(0000, '成功');
		}else{
			$this->ajaxReturnStatus(1000, '失败');
		}
	}
}