<?php

// +----------------------------------------------------------------------
// | FileName:   OrderController.class.bak.20170906.php
// +----------------------------------------------------------------------
// | Dscription:
// +----------------------------------------------------------------------
// | Date:  2017/8/22 15:14
// +----------------------------------------------------------------------
// | Author: showkw <showkw@163.com>
// +----------------------------------------------------------------------
namespace  Admin\Controller;
use Common\Controller\BaseController;
use Common\Controller\Category;
use Common\Controller\TreeController;
use Uba\Controller\EchartsController;
class SysController extends AdminController
{

    use Category;

	public static $order;

	protected function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        self::$order = D('order');
    }

    /**
     * @desc 账期类型列表
     *
     */
    public function accountTypeList(){
        if(IS_AJAX){
            $list=D('customeraccount')->accountTypeList();
            die(json_encode($list['data']['list']));
        }
    }
	
    /**
     * @desc 角色列表
     *
     */
    public function roleList(){
        $request=I('get.');
        $page=$request['page']?$request['page']:1;
        $pageSize=$request['pageSize']?$request['pageSize']:C('PAGE_PAGESIZE');
        $where=[];
        if(isset($request['role_id'])){
            $where['role_id']=$request['role_id'];
            $functions=D('sys')->functionShowTree($request['role_id']);
            $this->assign('functionTree',$functions['data']['list']);
        }

        $list=D('sys')->roleList($where,$page,$pageSize);

        $list['data']['page'] = $page;
        $list['data']['pageSize'] = $pageSize;
        if(IS_AJAX){
            die(json_encode(['error'=>0,'msg'=>'操作成功','data'=>$list['data']]));
        }
        $this->assign('list',$list['data']);
        $this->assign('request',$request);
        $this->display($request['url']);
    }

    /**
     * @desc 系统功能树
     *
     */
    public function sysFunction(){
        $request=I('get.');
        if(IS_AJAX){
            $functions=D('sys')->functionShowTree();
            die(json_encode(['error'=>0,'msg'=>'操作成功','data'=>$functions['data']['list']]));
        }
    }

    /**
     * @desc 系统功能初始化
     *
     */
    public function sysFunctinInit(){
        if(IS_AJAX){
            $result=D('sys')->sysFunctinInit();
            die(json_encode($result));
        }
    }

    /**
     * @desc 系统菜单
     *
     */
    public function sysMenuList(){
        $request=I('get.');
        $page=$request['page']?$request['page']:1;
        $pageSize=$request['pageSize']?$request['pageSize']:C('PAGE_PAGESIZE');
        $where=[];
        if(isset($request['menu_id'])) $where['menu_id']=$request['menu_id'];
        if(isset($request['menu_fid'])){
            $where['menu_fid']=$request['menu_fid'];
            $where=[$where,['menu_id'=>$request['menu_fid']],'_logic'=>'or'];
        }else{
            $where['menu_fid']=0;
        }
        $list=D('sysmenu')->sysMenuList($where,$page,$pageSize);
        $functionId_arr=(new \Admin\Model\BaseModel())->baseListType(M('function','sys_'),'*','function_id');
        foreach($list['data']['list'] as $k=>$v){
            if($v['menu_id']==$request['menu_fid']){
                $menuF=$list['data']['list'][$k];
                unset($list['data']['list'][$k]);
                continue;
            }
            $list['data']['list'][$k]['function_name']=$functionId_arr['data']['list'][$v['function_id']]['function_name'];
        }

        $menuFList=D('sysmenu')->sysMenuList(['menu_level'=>['in',[0,1]]]);

        $list['data']['page'] = $page;
        $list['data']['pageSize'] = $pageSize;
        $list['data']['list'] = array_values($list['data']['list']);
        $this->assign('list',$list['data']);
        $this->assign('menuF',$menuF);
        $this->assign('menuFList',$menuFList['data']['list']);
        $this->assign('request',$request);
        $this->display($request['url']);
    }

    /**
     * @desc 系统菜单编辑或添加
     *
     */
    public function sysMenuAction(){
        if(IS_AJAX){
            $request=I('post.');
            $result=D('sysmenu')->sysMenuAction($request);
            die(json_encode($result));
        }
    }

    /**
     * @desc 系统角色编辑或添加删除
     *
     */
    public function sysRoleAction(){
        if(IS_AJAX){
            $request=I('post.');
            $result=D('sys')->sysRoleAction($request);
            die(json_encode($result));
        }
    }

    /**
     * @desc 给系统角色添加或删除系统功能
     *
     */
    public function roleFunctionAction(){
        if(IS_AJAX){
            $request=I('post.');
            $result=(new \Admin\Model\SysModel())->roleFunctionAction($request);
            die(json_encode($result));
        }
    }

    public function test(){
        $list=D('user')->userFunctions(10000);
    }














}