<?php

// +----------------------------------------------------------------------
// | FileName:   OrderController.class.bak.20170906.php
// +----------------------------------------------------------------------
// | Dscription:
// +----------------------------------------------------------------------
// | Date:  2017/8/22 15:14
// +----------------------------------------------------------------------
// | Author: showkw <showkw@163.com>
// +----------------------------------------------------------------------
namespace  Admin\Controller;
use Common\Controller\BaseController;
use Common\Controller\Category;
use Common\Controller\TreeController;

class SysuserController extends AdminController
{

    use Category;

	public static $order;

	protected function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        self::$order = D('order');
    }

    /**
     * @desc 产品负责人列表
     *
     */
    public function productLiablePersionList(){
        if(IS_AJAX){
            $request=I('get.');
            $page=$request['page']?$request['page']:1;
            $pageSize=$request['pageSize']?$request['pageSize']:C('PAGE_PAGESIZE');

            $userM=D('user');
            $departmentId=C('DATA_POWER.product');
            $departmentInfo=$userM->userDepartments($departmentId);
            if($departmentInfo['error']!=0) die(json_encode($departmentInfo));
            $departmentId_arr=[$departmentId];
            foreach($departmentInfo['data']['son'] as $v){
                $departmentId_arr[]=$v['id'];
            }
            $where=['department_id'=>['in',$departmentId_arr]];//产品组编码
            if(isset($request['autoComplete'])&&$request['autoComplete']) $pageSize=200;
            $list=$userM->adminList($where,$page,$pageSize,'',true);
            if(isset($request['autoComplete'])&&$request['autoComplete']){
                $returnList=[];
                if($list['data']['list']){
                    foreach($list['data']['list'] as $k=>$v) {
                        $returnList['data'][] = $v['femplname'];
                        $returnList['index'][] = $v['uid'];
                    }
                }else{
                    $returnList['data'][]='没有数据';
                    $returnList['index'][]=0;
                }
                die(json_encode($returnList));
            }

            $list['data']['page'] = $page;
            $list['data']['pageSize'] = $pageSize;
            die(json_encode($list));
        }
    }

    /**
     * @desc 系统用户列表
     *
     */
    public function sysUserList(){
        $request=I('get.');
        $page=$request['page']?$request['page']:1;
        $pageSize=$request['pageSize']?$request['pageSize']:C('PAGE_PAGESIZE');
        $where=[];//产品组编码
        if(isset($request['user_name'])&&$request['user_name']) $where['user_name']=['like',"%$request[user_name]%"];
        if(isset($request['department_id'])&&$request['department_id']){
            $where['department_id']=$request['department_id'];
            $one=M('user_department','sys_')->field('lft,rht')->where(['id'=>$request['department_id']])->find();
            $father=M('user_department','sys_')->field('id')->where(['lft'=>['elt',$one['lft']],'rht'=>['egt',$one['rht']]])->order('lft')->select();
            $fatherPath=[];
            foreach($father as $k=>$v){
                $fatherPath[]=$v['id'];
            }
        }

        if(isset($request['name'])&&$request['name']){
            $syss=D('user')->sysNameToWhere($request['name']);
            if($syss['error']==0){
                $where['uid']=['in',$syss['data']];
            }
        }
        $list=D('user')->adminList($where,$page,$pageSize);
        $list['data']['page'] = $page;
        $list['data']['pageSize'] = $pageSize;
        //ajax获取列表
        if(IS_AJAX){
            die(json_encode(['error'=>0,'msg'=>'操作成功','data'=>$list['data']]));
        }
        $user=D('user');
        $departmentList=$user->sysUserDepartmentTree();
        $this->assign('tree',$departmentList['data']['category']);
        $this->assign('list',$list['data']);
        $this->assign('request',$request);
        $this->assign('fatherPath',$fatherPath);
        $this->display();
    }

    /**
     * @desc 系统用户添加或编辑或删除
     *
     */
    public function adminAction(){
        if(IS_AJAX){
            $request=I('post.');
            $result=D('user')->adminAction($request);
            die(json_encode($result));
        }
        $request=I('get.');
        $tree=D('user')->sysUserDepartmentTree();
        $list=D('user')->adminList(['uid'=>$request['uid']]);
        $categoryTree=D('category')->productCategoryInfinite(); //分类树
        if($categoryTree['error']!=0) die(json_encode($categoryTree));
        $this->assign('categoryTree',$categoryTree['data']);
        $this->assign('tree',$tree['data']['category']);
        $this->assign('request',$request);
        $this->assign('data',$list['data']['list'][0]);
        $this->display();
    }

    /**
     * @desc erp用户列表
     *
     */
    public function erpAdminList(){
        $request=I('get.');
        $page=$request['page']?$request['page']:1;
        $pageSize=$request['pageSize']?$request['pageSize']:C('PAGE_PAGESIZE');
        $where=[];
        if(isset($request['femplno'])) $where['femplno']=$request['femplno'];
        $erpAdminList=(new \Admin\Model\ErpcustomerModel())->erpAdminList($where,$page,$pageSize);
        if(IS_AJAX){
            die(json_encode($erpAdminList));
        }
    }

    /**
     * @desc 系统用户部门树
     *
     */
    public function sysUserDepartment()
    {
        $user=D('user');
        $list=$user->sysUserDepartmentTree();
        $departmentRole=$user->departmentRole();
        $request=I('get.');
        if(isset($request['id'])&&$request['id']){
            $where['department_id']=$request['id'];
            $one=M('user_department','sys_')->field('lft,rht')->where(['id'=>$request['id']])->find();
            $father=M('user_department','sys_')->field('id')->where(['lft'=>['elt',$one['lft']],'rht'=>['egt',$one['rht']]])->order('lft')->select();
            $fatherPath=[];
            foreach($father as $k=>$v){
                $fatherPath[]=$v['id'];
            }
        }
        $this->assign('list',$list['data']['category']);
        $this->assign('departmentRole',$departmentRole['data']);
        $this->assign('oneDepartment',M('user_department')->where(['id'=>I('get.id')])->find());
        $this->display();
    }

    /**
     * @desc 系统用户部门添加子部门或编辑
     *
     */
    public function sysUserDepartmentAdd(){
        if(IS_AJAX){
            $request=I('post.');
            if($request['action']=='edit'){
                $result=D('user')->sysUserDepartmentEdit($request);
                $result['id']=$request['id'];
                die(json_encode($result));
            }
            $result=D('user')->sysUserDepartmentAdd($request,$type='son');
            die(json_encode($result));
        }
    }

    /**
     * @desc 系统部门删除子部门
     *
     */
    public function sysUserDepartmentDelete(){
        if(IS_AJAX){
            $request=I('post.');
            $result=D('user')->sysUserDepartmentDelete($request);
            die(json_encode($result));
        }
    }

    /**
     * @desc 部门添加,删除角色
     *
     */
    public function departmentRoleAction(){
        if(IS_AJAX){
            $request=I('post.');
            $result=D('user')->departmentRoleAction($request);
            die(json_encode($result));
        }
    }

//    /**
//     * @desc 给用户添加下属部门
//     *
//     */
//    public function userAddDepartment(){
//        if(IS_AJAX){
//            $request=I('post.');
//            $result=D('user')->userAddDepartment($request);
//            die(json_encode($result));
//        }
//    }

    /**
     * @desc 消息通知列表
     *
     */
    public function adminNoteList(){
//        if(IS_AJAX){
            $sys_uId_arr=[session('adminId')];//自己的消息和所有下属的消息
            $list=D('user')->adminNoteList($sys_uId_arr);

            $return=[];
            if($list) $return=['error'=>0,'data'=>$list];
            else $return=['error'=>1,'msg'=>'没有消息'];
            die(json_encode($return));
//        }
    }

    /**
     * @desc 消息通知删除
     *   $request['index_arr']=[0,1];//消息下标
     *
     */
    public function adminNoteDelete(){
        if(IS_AJAX){
            $sys_uid=session('adminId');//只能删除自己的消息
            $request=I('post.');
            if(!is_array($request['index_arr'])) die(json_encode(['error'=>1,'msg'=>'参数错误']));
            $result=D('user')->adminNoteDelete($sys_uid,$request['index_arr']);
            die(json_encode(['error'=>0,'msg'=>'删除成功']));
        }
    }

    public function test(){
        $list=D('user')->adminMenu();
        print_r($list);
    }







}