<?php


// +----------------------------------------------------------------------
// | FileName:   OrderController.class.bak.20170906.php
// +----------------------------------------------------------------------
// | Dscription:
// +----------------------------------------------------------------------
// | Date:  2017/8/22 15:14
// +----------------------------------------------------------------------
// | Author: showkw <showkw@163.com>
// +----------------------------------------------------------------------
namespace  Admin\Controller;

class XCXuserController extends AdminController
{

	protected function _initialize()
	{
		parent::_initialize(); // TODO: Change the autogenerated stub
	}
 
    /**
     * @desc 小程序客户列表
     *
     */
    public function userList(){
        $request=I('get.');
        $page=$request['page']?$request['page']:1;
        $pageSize=$request['pageSize']?$request['pageSize']:C('PAGE_PAGESIZE');

        $where=['user_id'=>0];//游客

        $list=D('Admin/XCXuser','Logic')->userList($where,$page.','.$pageSize);

        $list['data']['page'] = $page;
        $list['data']['pageSize'] = $pageSize;
        $this->assign('list',$list['data']);
        $this->display();
    }


}