<?php
namespace Small\Controller;
use Think\Controller;
class BaseController extends Controller {
    public $post='';
    public $position='txt';
    public $openid;
    protected $userInfo;//商城客户信息
    public $session_key;
    public $session_token;
    public $return_data=[ 'data'=>'', 'statusCode'=>1, 'msg'=>'连接成功'];

    protected function _initialize()
    {
//        parent::_initialize(); // TODO: Change the autogenerated stub
//        $this->post=json_decode($GLOBALS['HTTP_RAW_POST_DATA'],true)?:$_POST;
        $this->post=json_decode(file_get_contents("php://input"),true)?:$_POST;
        if(APP_DEBUG) kelly_log(json_encode($this->post),'kelly_post','INFO');
        $this->return_data['request']=$this->post;

        $no_token=C('NO_TOKEN');
        $token=C('TOKEN');
        $controller_name=CONTROLLER_NAME;
        $function_name=ACTION_NAME;

        $customerInfo=$this->getCustomer($this->post['session_token']);
        $this->session_token=$this->post['session_token']?:'';
        $this->openid=$customerInfo[0]?:'';
        $this->session_key=$customerInfo[1]?:'';
        if(!isset($no_token[$controller_name][$function_name])){//token验证的接口
            if(isset($token[$controller_name][$function_name])){
                if(!isset($this->post['session_token'])||!$this->post['session_token']||!$customerInfo){
                    $this->return_data['statusCode']=-300;
                    $this->return_data['msg']='无效session_token';
                    $this->ajaxReturn($this->return_data);
                }else{
                    $this->saveCustomer($this->post['session_token'],$customerInfo);
                }
            }
        }
    }

    /**
     * @desc 获取客户信息
     *
     */
    public function getCustomer($key){
        if($this->position=='session'){
            return session($key);
        }else if($this->position=='txt'){
            return S($key);
        }
    }

    /**
     * @desc 存储客户信息
     *
     */
    public function saveCustomer($key,$value,$time='7200',$position=''){
        if(empty($position)) $position=$this->position;
        else $this->position=$position;
        if($position=='session'){
            session($key,$value);
        }else if($position=='txt'){
            S($key,$value,$time);
        }
    }

    /**
     * @desc 商城客户信息
     *
     */
    public function getUserInfo($session_id='',$die=true){

        $url_path=I('path.');
        $certification=1;
        if(($url_path[0]=="product"&&$url_path[1]=="productList")||((in_array($url_path[0],["Index","index"])&&$url_path[1]=="firstPageImg")) ||($url_path[0]=="category"&&$url_path[1]=="categoryTree")||($url_path[0]=="brand"&&$url_path[1]=="brandList")){
            $certification=0;
        }

//($url_path[0]=="memberCenter"&&$url_path[1]=="memberCenter")||

        if($this->userInfo) return $this->userInfo;

        $key=$this->post['session_token']?:$session_id;
        if(!$key) return ['用户信息错误'];
        $info=S($key);
        if($info['id']&&$this->userInfo=$info['userInfo']){
            return $this->userInfo;
        }elseif((!$info&&$certification)||(isset($info['userInfo'])&&(!isset($info["userInfo"]["xcx_user_id"])||!$info["userInfo"]["xcx_user_id"]||$info["userInfo"]["xcx_user_id"]=='null')&&$certification)) {
            $this->return_data['data']=[];
            $this->return_data['statusCode']=-300;
            $this->return_data['msg']="授权后才可以查看信息\n";
            $this->ajaxReturn($this->return_data);
        }else{
            $user_id = M('user', 'xcx_')->field('id as xcx_user_id,user_id,avatarurl')->where(['openid' => $info[0], 'appid' => $info[2]])->find();
            if ($die && !$user_id['user_id']) {
                $this->return_data['data'] = [];
                $this->return_data['statusCode'] = -500;
                $this->return_data['msg'] = '身份没有绑定';
                $this->ajaxReturn($this->return_data);
            }

            $info['userInfo'] = M('user')->field('fcustjc,user_name,user_mobile,nick_name,user_type,id')->where(['id' => $user_id['user_id']])->find();
            $info['userInfo']['avatarurl'] = $user_id['avatarurl'];
            $info['userInfo']['xcx_user_id'] = $user_id['xcx_user_id'];
            $this->userInfo = $info['userInfo'];
            $this->saveCustomer($key, $info);
            return $this->userInfo;
        }
    }




}