<?php

// +----------------------------------------------------------------------
// | FileName:   ImageController.class.php
// +----------------------------------------------------------------------
// | Dscription:
// +----------------------------------------------------------------------
// | Date:  2017/8/4 11:31
// +----------------------------------------------------------------------
// | Author: showkw <showkw@163.com>
// +----------------------------------------------------------------------
namespace Home\Controller;

use Common\Controller\BaseController;
use Common\Controller\Image;
use Home\Event\OrderEvent;

class ImageController extends BaseController
{
    use Image;
	public static $img = null;

	public $pdfImgPath = '';

	protected function _initialize()
	{
		parent::_initialize(); // TODO: Change the autogenerated stub
		self::$img = new \Think\Image(2);
		//获取PDf生成图片跟目录
		$this->pdfImgPath = getPdfImgeBasePath();
	}

	public function index()
	{
//        (new OrderEvent())->storeKdStateComplate();
//		$this->word2pdf();
//		$host = C('WEB_ROOT_DOMAIN');
//		foreach($imgsArr['big'] as $img){
//			echo '<img src="http://www.shop.com/'.$img.'"><br>';
//		}
//        de($this->thumb( SITE_PATH.'/Uploads/Pdf2Png/2018-02-01/82e2a11fea4ee072195b470671b259ba/big/img-0.png',SITE_PATH.'/Uploads/Pdf2Png/2018-02-01/82e2a11fea4ee072195b470671b259ba/small/','img-0',174,248,true,false ));
		die();
	}

}