<?php

// +----------------------------------------------------------------------
// | FileName:   ProductController.class.php
// +----------------------------------------------------------------------
// | Dscription:   产品控制器类
// +----------------------------------------------------------------------
// | Date:  2017/8/7 12:45
// +----------------------------------------------------------------------
// | Author: showkw <showkw@163.com>
// +----------------------------------------------------------------------

namespace Home\Controller;

use Admin\Controller\MsgController;
use Home\Controller\HomeController;
use Org\ThinkSDK\sinaClient;
use Org\ThinkSDK\ThinkOauth;
use Home\Controller\DefaultController;


class ProductController extends HomeController
{
	public $category_list;
	public $brand_list;
	
	public $upload_root = '';
	
	protected function _initialize()
	{
		parent::_initialize(); // TODO: Change the autogenerated stub
		$this->upload_root = rtrim( SITE_PATH, DIRECTORY_SEPARATOR ) . DIRECTORY_SEPARATOR . rtrim( C( 'UPLOAD_ROOT' ), DIRECTORY_SEPARATOR ) . '/';
	}
	
	/*
	 * 商品详情页
	 *
	 */
	public function detail()
	{
		$request=I('get.');
        $request=executePurifier($request);
		$pro = D( 'Product' );
		$productWhere=[];
		if( isset( $request['sign'] )&& $request['sign'] ){
		    $productWhere=['p_sign'=>$request['sign'] ];
        }else{
		    $this->error( '商品信息错误' ,U('Home/Default/index'));
        }
        $productWhere=[$productWhere];
		$info_result=$this->productList($productWhere);
		$info=($info_result['error']==0)?$info_result['data']['list'][0]:'';
		$p_id=$info['id'];
        //生成分享二维码
        $result=D('Small/XCXAPI','Logic')->createQRcodeShare(1744,$p_id,'wx6a1319c215b146fd','c0821fa195b3de9000595226ec033a43','01');
        if($result['error']==0 && file_exists(SITE_PATH.$result['data']['path'])){
            $wx_code=$result['data']['path'];
        }else{
            $wx_code='';
        }
		//计算最小盘数
		$min = floatval($info['min']);//最小包装
		$minOrder = floatval($info['minorder']); //最小起订量
		if( empty($minOrder) ){
			$info['minorder'] = 0;
			$default['pan'] = 0;
			$default['k'] = 0;
			$default['g'] = 0;
		}else{
			if( $minOrder < $min ){
				$default['pan'] = 0;
				if( $minOrder > 1000 ){
					$default['k'] = floor($minOrder/1000);
					$default['g'] = $minOrder-($default['k']*1000);
				}
			}elseif( $minOrder == $min ){
				$default['pan'] = 1;
				$default['k'] = $default['g'] = 0;
			}else{
				$default['pan'] = floor($minOrder/$min);
				$default['k'] = floor(($minOrder-$default['pan']*$min)/1000);
				$default['g'] = $minOrder-($default['pan']*$min )-($default['k']*1000);
			}
		}
		$this->assign('default',$default);
		//$path = $this->getCatePath( $info[ 'cate_id' ] );
		$info[ 'pdfImg' ] = $this->getPdfImgs( $p_id );
		//若用户登录
		if ( is_login() ) {
			//获取用户收藏夹列表
			$user_id = session( 'userId' );
			$result = D( 'user_collect' )->where( [ 'user_id' => $user_id ] )->find();
			$collectArr = json_decode( $result[ 'collect' ], true );
			if ( in_array( $p_id, $collectArr ) ) {
				$this->assign( 'collected', 1 );
			} else {
				$this->assign( 'collected', 0 );
			}
			//加入用户浏览足迹
			$this->addHistory( $p_id, $user_id );
		}
		//商品点击量加1
		$ip = session( 'userIp' );
		$uid = session( 'userId' ) ? session( 'userId' ) : 0;
		if ( !S( 'click_' . $ip . '_' . $uid ) ) {
			$pro->where( [ 'id' => $p_id ] )->setInc( 'click_num' );
			S( 'click_' . $ip . '_' . $uid, 'clicked', 10 ); //10秒内 同一ip同一账号点击只算一次
		}
		if ( IS_AJAX ) {
			$this->ajaxReturn( $info, 'json' );
		}
		if ( IS_GET ) {
			$this->assign( 'p_id', $p_id );
			$user_id = session( 'userId' );
			if ( $user_id ) {//用户登录
				$user_basket = D( 'basket' )->where( [ 'user_id' => $user_id ] )->find();
				$basket_id = $user_basket[ 'basket_id' ];
			} else {//用户未登录
				$basket = new \Home\Controller\BasketController();
				$basket_id = $basket->notLoginBasketId();
			}
			$basket_goods = D( 'basket_detail' )->where( [ 'pid' => $p_id, 'basket_id' => $basket_id ] )->find();
			//客户qq,wechart
            $adminList=M('user','sys_')->field('nickname,qq,wechat,mobile,product_category')->where(['is_customer_service'=>1])->select();
            $customer_service=[];
            foreach($adminList as $k2=>$v2){
                if(strpos($v2['product_category'],",$info[cate_id],")!==false){
                    $customer_service[]=$v2;
                }

            }
			$this->assign( 'customer_service',$customer_service );
			$this->assign( 'path', $path );
			$this->assign( 'info', $info );
            $this->assign('wx_code',$wx_code);
			$this->assign( 'basket_goods', $basket_goods );
			$this->assign( 'price', $info[ 'price' ] );
			$this->assign( 'attr', $info[ 'attr' ] );
			$this->assign( 'pdfImg', $info[ 'pdfImg' ] );
			$this->assign( 'big', $info[ 'pdfImg' ][ 'big' ] );
			$this->assign( 'small', $info[ 'pdfImg' ][ 'small' ] );
			$this->display();
		}
	}
	
	
	/*
	 * 详情页下载pdf
	 *
	 */
	public function downPdf( $p_id = 1 )
	{
		$p_id = I( 'p_id' ) ? I( 'p_id' ) : $p_id;
		//详情表查询
		$detail = M( 'product_detail' );
		$pro = M( 'product' )->field( 'p_sign' )->where( [ 'id' => $p_id ] )->find();
		$info = $detail->field( 'pdf' )->where( [ 'p_id' => $p_id ] )->find();
		$pdf = SITE_PATH  . $info[ 'pdf' ];

		header( 'Content-type: application/pdf' );
		header( 'Content-Disposition: attachment; filename="' . $pro[ 'p_sign' ]. '.pdf"' );
		readfile( $pdf );
		exit();
	}
	
	/*
	 *
	 * 获取pdf转化的图片
	 * @param $p_id  int 产品id
	 * @return  array  相对于上次文件目录下的相对图片地址
	 *
	 */
	public function getPdfImgs( $p_id )
	{
		$res = M('product_detail')->where(['p_id'=>$p_id])->find();
		if( $res && $res['img_path'] ){
			$imgAll = ['png','jpg','jpeg','bmp'];
			//相对路径
			$basePath = trim($res['img_path'],'/');
			//绝对路径
			$path = SITE_PATH.$basePath;
			//扫描目录 原图目录
			$imageNames = scandir($path.'/big');
			//排序
			sort($imageNames,SORT_NATURAL);
			foreach($imageNames as $key =>$name){
				//获取扩展
				$ext = getExtension($path.'\\bug\\'.$name);
				if( $name != '.' && $name != '..' && in_array($ext, $imgAll) ){
					$imgsArr['big'][] = '/'.$basePath.'/big/'.$name;
				}
			}
			//缩略图
			$thumbImageNames = scandir($path.'/small');
			sort($thumbImageNames,SORT_NATURAL);
			$coverExt = 'png';
			foreach($thumbImageNames as $key =>$name){
				//获取扩展
				$ext = getExtension($path.'\\small\\'.$name);
				if( $key === 0 ){
					$coverExt = $ext;
				}
				if( $name != '.' && $name != '..' && in_array($ext, $imgAll) ){
					$imgsArr['small'][] = '/'.$basePath.'/small/'.$name;
				}
			}
			//缩略封面图
			$imgsArr['cover'] = '/'.$basePath.'/cover.png';
		}else{
			$imgsArr = [];
		}

		return $imgsArr;
	}
	
	/*
	 *
	 * PDF文件转图片 (弃用)
	 * @param  $pdf  待转换的pdf文件地址
	 * @param  $imgDir  生成后图片保存目录
	 *
	 */
	public function pdf2png( $pdf, $imgDir )
	{
		if ( !extension_loaded( 'imagick' ) ) {
			return 1;//未安装imagick扩展
		}
		if ( !file_exists( $pdf ) ) {
			return 2;//pdf文件不存在
		}
		$type = strtolower( C( 'PDF2IMG_TYPE' ) );
		$allType = [ 'png', 'jpg', 'jpeg', 'bmp' ];
		if ( !in_array( $type, $allType ) ) {
			return 3;//只允许转换'png','jpg','jpeg','bmp'图片格式
		}
		$IM = new \Imagick();
		$IM->setResolution( 100, 100 );
		$IM->setCompressionQuality( 100 );
		$IM->readImage( $pdf );
		foreach ( $IM as $key => $var ) {
			$var->setImageFormat( $type );
			$fileName = $imgDir . '/big/image-' . $key . '.' . $type;//相对于Uploads路径 原图
			$baseName = $this->upload_root . $fileName;//绝对路径 原图
			$thumbName = $this->upload_root . $imgDir . '/small/image-' . $key . '.' . $type; //缩略图
			$coverName = $this->upload_root . $imgDir . '/cover.' . $type;
			if ( $var->writeImage( $baseName ) == true ) {
				//生成缩略图
				if ( $key == 0 ) {
					// 生成封面图 122*147
					$image = new \Think\Image();
					$image->open( $baseName );
					$image->thumb( 122, 147, 1 )->save( $coverName );
				}
				//生成缩略图
				$image = new \Think\Image();
				$image->open( $baseName );
				$image->thumb( 173, 224, 1 )->save( $thumbName );
				$Return[ 'big' ][] = '/' . $fileName;//原图
				$Return[ 'small' ][] = '/' . $imgDir . '/small/image-' . $key . '.' . $type;//缩略图
				$Return[ 'cover' ] = '/' . $imgDir . '/cover.' . $type;
			}
		}
		
		return $Return;
	}
	
	/*
	 *
	 *  获取指定分类id 的分类路径信息
	 */
	public function getCatePath( $cate_id )
	{
		$cate_id = intval( $cate_id );
		empty( $cate_id ) && exit();
		$cate = D( 'category' );
		$path = [];
		$info = $cate->where( [ 'id' => $cate_id ] )->find();
		if ( $info[ 'path' ] == '0,' ) {
			$path[] = [ 'id' => $cate_id, 'name' => $info[ 'cate_name' ] ];
		} else {
			$pathArr = explode( ',', rtrim( $info[ 'path' ], ',' ) );
			foreach ( $pathArr as $k => $value ) {
				if ( $value != 0 ) {
					$data = $cate->where( [ 'id' => intval( $value ) ] )->find();
					$path[] = [ 'id' => intval( $value ), 'name' => $data[ 'cate_name' ] ];
				}
			}
			$path[] = [ 'id' => $cate_id, 'name' => $info[ 'cate_name' ] ];
		}
		
		return $path;
	}
	/*
	 *搜索条件范围
	 * @param string search 搜索基本条件
	 * @param string current 电流,用逗号拼接
	 * @param string input 输入电压,用逗号拼接
	 * @param string output 输出电压,用逗号拼接
	 * @param string brand_id 品牌ID,用逗号拼接
	 * @param string cate_id 分类ID,用逗号拼接
	 * @param string package 封装,用逗号拼接
	 * @return object json
 	 */
	public function requireSearch(){
		$request = I( 'post.' );
		$where=[];
		//功能条件
        $where['dp.is_online']=['eq',1];
        if($request['search_type']=='hot_function'){
            if($request['search']){
                $where[]=[
                    'dp.parameter'=>['like',"%$request[search]%"],
                    'dp.describe'=>['like',"%$request[search]%"],
                    '_logic'=>'or'
                ];
            }
        }elseif ($request['search_type']=='hot_brand'){
            if($request['search']){
                $brandName=M('brand')->field('id')->where(['brand_name'=>['like',"%$request[search]%"]])->select();
                if($brandName){
                    $brandId_arr=[];
                    foreach($brandName as $k=>$v){
                        $brandId_arr[]=$v['id'];
                    }
                    if(isset($request['brand_id'])&&$request['brand_id']){
                        $brandArr=explode(',',$request['brand_id']);
                        $request['brand_id']=array_intersect($brandId_arr,$brandArr);
                    }else{
                        $request['brand_id']=implode(',',$brandId_arr);
                    }
                }else{

                    $request['brand_id']=$request['brand_id'];
                }
            }
        }elseif ($request['search_type']=='hot_pSign'){
            if($request['search']) {
                if(session('adminId')){//只有管理员可以搜索erp型号
                    $where[]=[
                        'fitemno_access'=>[ 'like', '%' . $request['search'] . '%' ],
                        'fitemno'=>[ 'like', '%' . $request['search'] . '%' ],
                        'p_sign'=>[ 'like', '%' . $request['search'] . '%' ],
                        'p_sign in (select p_sign from dx_product_fitemno where fitemno like "%'.$request['search'].'%")',
                        '_logic'=>'or'
                    ];
                }else{
                    $where[]=[
                        'fitemno_access'=>[ 'like', '%' . $request['search'] . '%' ],
                        'p_sign'=>[ 'like', '%' . $request['search'] . '%' ],
                        '_logic'=>'or'
                    ];
                }
            }
        }
//        //电流范围
//
//        if($request['current']!=''&&$request['current']!=','){
//            $request['current']=explode(',',$request['current']);
//            if($request['current'][1]){
//                if(!$request['current'][0]){
//                    $request['current'][0]=0;
//                }
//                sort($request['current']);
//                $where['current_start']=['elt',$request['current'][0]*1000];
//                $where['current_end']=[
//                    ['egt',$request['current'][1]*1000],
//                    ['eq',0],
//                    'or'
//                ];
//            }else{
//                $where['current_start']=[
//                    ['eq',$request['current'][0]*1000]
//                ];
//
//            }
//        }
//        //输入电压范围
//
//        if($request['input']!=''&&$request['input']!=','){
//            $request['input']=explode(',',$request['input']);
//            if($request['input'][1]){
//                if(!$request['input'][0]){
//                    $request['input'][0]=0;
//                }
//                sort($request['input']);
//                $where['voltage_input_start']=['elt',$request['input'][0]*1000];
//                $where['voltage_input_end']=[
//                    ['egt',$request['input'][1]*1000],
//                    ['eq',0],
//                    'or'
//                ];
//            }else{
//                $where['voltage_input_end']=[
//                    ['eq',$request['input'][0]*1000]
//                ];
//
//            }
//        }
//        //输入电压范围
//        if($request['output']!=''&&$request['output']!=','){
//            $request['output']=explode(',',$request['output']);
//            if($request['output'][1]){
//                if(!$request['output'][0]){
//                    $request['output'][0]=0;
//                }
//                sort($request['output']);
//                $where['voltage_output_start']=['elt',$request['output'][0]*1000];
//                $where['voltage_output_end']=[
//                    ['egt',$request['output'][1]*1000],
//                    ['eq',0],
//                    'or'
//                ];
//            }else{
//                $where['voltage_output_start']=[
//                    ['eq',$request['output'][0]*1000]
//                ];
//
//            }
//        }
        if(isset($request['attr_id'])&&$request['attr_id']){
            $typeRes=M("product_attribute_type")->where(['id'=>$request['attr_id']])->find();
            if($typeRes){
                if($typeRes['current']){
                    if($typeRes['current_type']==1){
                        //体积
                        if($request['current']){
                            $where[]=[
                                'current_start'=>['IN',$request['current']],
                            ];
                        }
                    }else{
                        //范围值
                        if($request['current']!=''&&$request['current']!=','){
                            $request['current']=explode(',',$request['current']);
                            if($request['current'][1]){
                                if(!$request['current'][0]){
                                    $request['current'][0]=0;
                                }
                                sort($request['current']);
                                $where1['current_start']=['elt',$request['current'][0]*1000];
                                $where1['current_end']=[
                                    ['egt',$request['current'][1]*1000],
                                ];


                                $where2['current_start']=['between',[$request['current'][0]*1000,$request['current'][1]*1000]];
                                $where2['current_end']=['eq',0];
                                $where[]=[$where1,$where2,'_logic'=>'or'];
                            }else{
                                $where['current_start']=[
                                    ['eq',$request['current'][0]*1000]
                                ];

                            }
                        }
                    }
                }

                if($typeRes['voltage_input']){
                    if($typeRes['voltage_input_type']==1){
                        //体积
                        if($request['voltage_input']){
                            $where[]=[
                                'voltage_input_start'=>['IN',$request['voltage_input']],
                            ];
                        }
                    }else{
                        //输入电压范围
                        if($request['voltage_input']!=''&&$request['voltage_input']!=','){
                            $request['voltage_input']=explode(',',$request['voltage_input']);
                            if($request['voltage_input'][1]){
                                if(!$request['voltage_input'][0]){
                                    $request['voltage_input'][0]=0;
                                }
                                sort($request['voltage_input']);
                                $where1['voltage_input_start']=['elt',$request['voltage_input'][0]*1000];
                                $where1['voltage_input_end']=[
                                    ['egt',$request['voltage_input'][1]*1000],
                                ];
                                $where2['voltage_input_start']=['between',[$request['voltage_input'][0]*1000,$request['voltage_input'][1]*1000]];
                                $where2['voltage_input_end']=['eq',0];
                                $where[]=[$where1,$where2,'_logic'=>'or'];
                            }else{
                                $where['voltage_input_end']=[
                                    ['eq',$request['voltage_input'][0]*1000]
                                ];

                            }
                        }


                    }
                }

                if($typeRes['voltage_output']){
                    if($typeRes['voltage_output_type']==1){
                        //体积
                        if($request['voltage_output']){
                            $where[]=[
                                'voltage_output_start'=>['IN',$request['voltage_output']],
                            ];
                        }
                    }else{
                        //输入电压范围
                        if($request['voltage_output']!=''&&$request['voltage_output']!=','){
                            $request['voltage_output']=explode(',',$request['voltage_output']);
                            if($request['voltage_output'][1]){
                                if(!$request['voltage_output'][0]){
                                    $request['voltage_output'][0]=0;
                                }
                                sort($request['voltage_output']);
                                $where1['voltage_output_start']=['elt',$request['voltage_output'][0]*1000];
                                $where1['voltage_output_end']=[
                                    ['egt',$request['voltage_output'][1]*1000],
                                ];
                                $where2['voltage_output_start']=['between',[$request['voltage_output'][0]*1000,$request['voltage_output'][1]*1000]];
                                $where2['voltage_output_end']=['eq',0];
                                $where[]=[$where1,$where2,'_logic'=>'or'];
                            }else{
                                $where['voltage_output_start']=[
                                    ['eq',$request['voltage_output'][0]*1000]
                                ];

                            }
                        }


                    }
                }

                if($typeRes['volume']){
                    if($typeRes['volume_type']==1){
                        //体积
                        if($request['volume']){
                            $where[]=[
                                'volume_length'=>['IN',$request['volume']],
                            ];
                        }
                    }else{
                        //输入电压范围
                        if($request['volume']!=''&&$request['volume']!=','){
                            $request['output']=explode(',',$request['volume']);
                            if($request['volume'][1]){
                                if(!$request['volume'][0]){
                                    $request['volume'][0]=0;
                                }
                                sort($request['volume']);
                                $where1['volume_length']=['elt',$request['volume'][0]*1000];
                                $where1['volume_width']=[
                                    ['egt',$request['volume'][1]*1000],
                                ];
                                $where2['volume_length']=['between',[$request['volume'][0]*1000,$request['volume'][1]*1000]];
                                $where2['volume_width']=['eq',0];
                                $where[]=[$where1,$where2,'_logic'=>'or'];
                            }else{
                                $where['volume_length']=[
                                    ['eq',$request['volume'][0]*1000]
                                ];

                            }
                        }


                    }
                }
                if($typeRes['custom']){
                    if($typeRes['custom_type']==1){
                        //体积
                        if($request['custom']){
                            $where[]=[
                                'custom_start'=>['IN',$request['custom']],
                            ];
                        }
                    }else{
                        //输入电压范围
                        if($request['custom']!=''&&$request['custom']!=','){
                            $request['custom']=explode(',',$request['custom']);
                            if($request['custom'][1]){
                                if(!$request['custom'][0]){
                                    $request['custom'][0]=0;
                                }
                                sort($request['custom']);
                                $where1['custom_start']=['elt',$request['custom'][0]*1000];
                                $where1['custom_end']=[
                                    ['egt',$request['custom'][1]*1000],
                                ];

                                $where2['custom_start']=['between',[$request['custom'][0]*1000,$request['custom'][1]*1000]];
                                $where2['custom_end']=['eq',0];
                                $where[]=[$where1,$where2,'_logic'=>'or'];
                            }else{
                                $where['custom_start']=[
                                    ['eq',$request['custom'][0]*1000]
                                ];

                            }
                        }


                    }
                }
                if($typeRes['custom1']){
                    if($typeRes['custom1_type']==1){
                        //体积
                        if($request['custom1']){
                            $where[]=[
                                'custom1_start'=>['IN',$request['custom1']],
                            ];
                        }
                    }else{
                        //输入电压范围
                        if($request['custom1']!=''&&$request['custom1']!=','){
                            $request['custom1']=explode(',',$request['custom1']);
                            if($request['custom1'][1]){
                                if(!$request['custom1'][0]){
                                    $request['custom1'][0]=0;
                                }
                                sort($request['custom1']);
                                $where1['custom1_start']=['elt',$request['custom1'][0]*1000];
                                $where1['custom1_end']=[
                                    ['egt',$request['custom1'][1]*1000],
                                ];

                                $where2['custom1_start']=['between',[$request['custom1'][0]*1000,$request['custom1'][1]*1000]];
                                $where2['custom1_end']=['eq',0];
                                $where[]=[$where1,$where2,'_logic'=>'or'];
                            }else{
                                $where['custom1_start']=[
                                    ['eq',$request['custom1'][0]*1000]
                                ];

                            }
                        }


                    }
                }
                if($typeRes['custom2']){
                    if($typeRes['custom2_type']==1){
                        //体积
                        if($request['custom2']){
                            $where[]=[
                                'custom2_start'=>['IN',$request['custom2']],
                            ];
                        }
                    }else{
                        //输入电压范围
                        if($request['custom2']!=''&&$request['custom2']!=','){
                            $request['custom2']=explode(',',$request['custom2']);
                            if($request['custom2'][1]){
                                if(!$request['custom2'][0]){
                                    $request['custom2'][0]=0;
                                }
                                sort($request['custom2']);
                                $where1['custom2_start']=['elt',$request['custom2'][0]*1000];
                                $where1['custom2_end']=[
                                    ['egt',$request['custom2'][1]*1000],
                                ];

                                $where2['custom2_start']=['between',[$request['custom2'][0]*1000,$request['custom2'][1]*1000]];
                                $where2['custom2_end']=['eq',0];
                                $where[]=[$where1,$where2,'_logic'=>'or'];
                            }else{
                                $where['custom2_start']=[
                                    ['eq',$request['custom2'][0]*1000]
                                ];

                            }
                        }


                    }
                }





            }


        }


        //封装
		if($request['package']){
			$where[]=[
				'dp.package'=>['IN',$request['package']],
			];
		}
		//品牌
		if($request['brand_id']){
			$where[]=[
				'dp.brand_id'=>['IN',$request['brand_id']],
			];
		}
        //分类
        if(isset($request['cate_id'])&&$request['cate_id']){
            $caId=explode(',',$request['cate_id']);
            $caId=array_filter($caId);
            $request['cate_id']=implode(',',$caId);
            $where[]=[
                'cate_id in (select id from dx_category left join (select * from (select lft as lft2,rht as rht2 from dx_category where id IN ('.$request['cate_id'].')) as lef_rht) as lef_rht2 on 1=1 where dx_category.lft>=lef_rht2.lft2 and dx_category.rht<=lef_rht2.rht2)'
            ];
        }
//		//体积
//		if($request['volume_length']){
//			$where[]=[
//				'dpa.volume_length'=>['IN',$request['volume_length']],
//			];
//		}
		$screen=M('product')->alias("dp")->field("dp.id,dp.brand_id,dxb.brand_name,dp.cate_id,dc.cate_name,dp.package,dpa.current_start,dpa.current_end,dpa.voltage_input_start,dpa.voltage_input_end,dpa.voltage_output_start,dpa.voltage_output_end,dpa.volume_length,dpa.volume_width,dpa.custom_start,dpa.custom_end,dpa.custom1_start,dpa.custom1_end,dpa.custom2_start,dpa.custom2_end,attr_id")->join("dx_brand as dxb on dxb.id=dp.brand_id")->join("dx_category as dc on dc.id=dp.cate_id")->join("dx_product_attribute as dpa on dpa.id=dp.id")->where($where)->select();
        $res['brand']=array_column($screen,'brand_name','brand_id');
		$res['cate']=array_column($screen,'cate_name','cate_id');
		$res['package']=array_column($screen,'package','package');
//		//第二个0代表无穷大
//        $cArr=array_merge(array_column($screen,'current_start'),array_column($screen,'current_end'));
//        $iArr=array_merge(array_column($screen,'voltage_input_start'),array_column($screen,'voltage_input_end'));
//        $oArr=array_merge(array_column($screen,'voltage_output_start'),array_column($screen,'voltage_output_end'));
//		$res['current']=(min($cArr)/1000).','.(max($cArr)/1000);
//		$res['input']=(min($iArr)/1000).','.(max($iArr)/1000);
//		$res['output']=(min($oArr)/1000).','.(max($oArr)/1000);
//		//体积
//		$res['volume_length']=array_column($screen,volume_length,volume_length);
        $cate_id=array_column($screen,'cate_id','cate_id');
        if(count($cate_id)==1){
            foreach ($cate_id as $v){
                $where2= 'find_in_set('.$v.',cate_id) ';
                $res_attr=M("product_attribute_type")->where($where2)->find();
            }
            if($res_attr)  $res['cid']=$res_attr;
            if(isset($res_attr['current'])&&$res_attr['current']){
                if($res_attr['current_type']==1){
                    $res['current']=array_column($screen,'current_start','current_start');
                    foreach ($res['current'] as &$v){
                        $v=$v/1000;
                    }
                }else{
                    $cArr=array_merge(array_column($screen,'current_start'),array_column($screen,'current_end'));
                    $res['current']=(min($cArr)/1000).','.(max($cArr)/1000);
                }
            }
            if(isset($res_attr['voltage_input'])&&$res_attr['voltage_input']){
                if($res_attr['voltage_input_type']==1){
                    $res['voltage_input']=array_column($screen,'voltage_input_start','voltage_input_start');
                    foreach ($res['voltage_input'] as &$v){
                        $v=$v/1000;
                    }
                }else{
                    $iArr=array_merge(array_column($screen,'voltage_input_start'),array_column($screen,'voltage_input_end'));
                    $res['voltage_input']=(min($iArr)/1000).','.(max($iArr)/1000);
                }
            }
            if(isset($res_attr['voltage_output'])&&$res_attr['voltage_output']){
                if($res_attr['voltage_output_type']==1){
                    $res['voltage_output']=array_column($screen,'voltage_output_start','voltage_output_start');
                    foreach ($res['voltage_output'] as &$v){
                        $v=$v/1000;
                    }
                }else{
                    $oArr=array_merge(array_column($screen,'voltage_output_start'),array_column($screen,'voltage_output_end'));
                    $res['voltage_output']=(min($oArr)/1000).','.(max($oArr)/1000);
                }
            }
            if(isset($res_attr['volume'])&&$res_attr['volume']){
                if($res_attr['volume_type']==1){
                    $res['volume']=array_column($screen,'volume_length','volume_length');
                    foreach ($res['volume'] as &$v){
                        $v=$v/1000;
                    }
                }else{
                    $vArr=array_merge(array_column($screen,'volume_length'),array_column($screen,'volume_width'));
                    $res['volume']=(min($oArr)/1000).','.(max($vArr)/1000);
                }
            }
            if(isset($res_attr['custom'])&&$res_attr['custom']){
                if($res_attr['custom_type']==1){
                    $res['custom']=array_column($screen,'custom_start','custom_start');
                    foreach ($res['custom'] as &$v){
                        $v=$v/1000;
                    }
                }else{
                    $cuArr=array_merge(array_column($screen,'custom_start'),array_column($screen,'custom_end'));
                    $res['custom']=(min($cuArr)/1000).','.(max($cuArr)/1000);
                }
            }
            if(isset($res_attr['custom1'])&&$res_attr['custom1']){
                if($res_attr['custom1_type']==1){
                    $res['custom1']=array_column($screen,'custom1_start','custom1_start');
                    foreach ($res['custom1'] as &$v){
                        $v=$v/1000;
                    }
                }else{
                    $cuArr=array_merge(array_column($screen,'custom1_start'),array_column($screen,'custom1_end'));
                    $res['custom1']=(min($cuArr)/1000).','.(max($cuArr)/1000);
                }
            }
            if(isset($res_attr['custom2'])&&$res_attr['custom2']){
                if($res_attr['custom2_type']==1){
                    $res['custom2']=array_column($screen,'custom2_start','custom2_start');
                    foreach ($res['custom2'] as &$v){
                        $v=$v/1000;
                    }
                }else{
                    $cuArr=array_merge(array_column($screen,'custom2_start'),array_column($screen,'custom2_end'));
                    $res['custom2']=(min($cuArr)/1000).','.(max($cuArr)/1000);
                }
            }
//            //第二个0代表无穷大
//            $cArr=array_merge(array_column($screen,'current_start'),array_column($screen,'current_end'));
//            $iArr=array_merge(array_column($screen,'voltage_input_start'),array_column($screen,'voltage_input_end'));
//            $oArr=array_merge(array_column($screen,'voltage_output_start'),array_column($screen,'voltage_output_end'));
//            $res['current']=(min($cArr)/1000).','.(max($cArr)/1000);
//            $res['input']=(min($iArr)/1000).','.(max($iArr)/1000);
//            $res['output']=(min($oArr)/1000).','.(max($oArr)/1000);
            //体积
          //  $res['volume_length']=array_column($screen,volume_length,volume_length);
        }
		return $res;
		//die(json_encode($res));
	}
	/*
	 *  商品列表
	 */
	public function search()
	{
        $request = I( 'post.' );
        $request=executePurifier($request);
        $where=[];

		//用户购物车里的商品
        $user_id = session( 'userId' );
		if ( $user_id ) {//用户登录
			$user_basket = D( 'basket' )->where( [ 'user_id' => $user_id ] )->find();
			$basket_id = $user_basket[ 'basket_id' ];
		} else {//用户未登录
			$basket = new \Home\Controller\BasketController();
			$basket_id = $basket->notLoginBasketId();
		}
        $ret=$this->requireSearch();
		if(isset($ret['cid'])){
		    $this->assign('changeName',$ret['cid']);
		    unset($ret['cid']);
        }
        //print_r($ret);
        $this->assign('ret',$ret);
        if ($request['search_type']=='hot_brand'){
            if($request['search']){
                $brandName=M('brand')->field('id')->where(['brand_name'=>['like',"%$request[search]%"]])->select();
                if($brandName){
                    $brandId_arr=[];
                    foreach($brandName as $k=>$v){
                        $brandId_arr[]=$v['id'];
                    }
                    if(isset($request['brand_id'])&&$request['brand_id']){
                        $brandArr=explode(',',$request['brand_id']);
                        $request['brand_id']=array_intersect($brandId_arr,$brandArr);
                    }else{
                        $request['brand_id']=implode(',',$brandId_arr);
                    }
                }else{

                    $request['brand_id']=$request['brand_id'];
                }
            }
        }
        //品牌ID
        if($request['brand_id']){
            $where[]=[
                'brand_id'=>['IN',$request['brand_id']],
            ];
        }
        //分类
        if(isset($request['cate_id'])&&(int)$request['cate_id']){
            $caId=explode(',',$request['cate_id']);
            $caId=array_filter($caId);
            $request['cate_id']=implode(',',$caId);
            $where[]=[
                'cate_id in (select id from dx_category left join (select * from (select lft as lft2,rht as rht2 from dx_category where id IN ('.$request['cate_id'].')) as lef_rht) as lef_rht2 on 1=1 where dx_category.lft>=lef_rht2.lft2 and dx_category.rht<=lef_rht2.rht2)'
            ];
        }
        //封装ID
        if($request['package']){
            $where[]=[
                'package'=>['IN',$request['package']],
            ];
        }

        if(isset($request['attr_id'])&&$request['attr_id']){
            $typeRes=M("product_attribute_type")->where(['id'=>$request['attr_id']])->find();
            if($typeRes){
                if($typeRes['current']){
                    if($typeRes['current_type']==1){
                        //体积
                        if($request['current']){
                            $where[]=[
                                'current_start'=>['IN',$request['current']],
                            ];
                        }
                    }else{
                        //范围值
                        if($request['current']!=''&&$request['current']!=','){
                            $request['current']=explode(',',$request['current']);
                            if($request['current'][1]){
                                if(!$request['current'][0]){
                                    $request['current'][0]=0;
                                }
                                sort($request['current']);
                                $where1['current_start']=['elt',$request['current'][0]*1000];
                                $where1['current_end']=[
                                    ['egt',$request['current'][1]*1000],
                                ];


                                $where2['current_start']=['between',[$request['current'][0]*1000,$request['current'][1]*1000]];
                                $where2['current_end']=['eq',0];
                                $where[]=[$where1,$where2,'_logic'=>'or'];
                            }else{
                                $where['current_start']=[
                                    ['eq',$request['current'][0]*1000]
                                ];

                            }
                        }
                    }
                }

                if($typeRes['voltage_input']){
                    if($typeRes['voltage_input_type']==1){
                        //体积
                        if($request['voltage_input']){
                            $where[]=[
                                'voltage_input_start'=>['IN',$request['voltage_input']],
                            ];
                        }
                    }else{
                        //输入电压范围
                        if($request['voltage_input']!=''&&$request['voltage_input']!=','){
                            $request['voltage_input']=explode(',',$request['voltage_input']);
                            if($request['voltage_input'][1]){
                                if(!$request['voltage_input'][0]){
                                    $request['voltage_input'][0]=0;
                                }
                                sort($request['voltage_input']);
                                $where1['voltage_input_start']=['elt',$request['voltage_input'][0]*1000];
                                $where1['voltage_input_end']=[
                                    ['egt',$request['voltage_input'][1]*1000],
                                ];
                                $where2['voltage_input_start']=['between',[$request['voltage_input'][0]*1000,$request['voltage_input'][1]*1000]];
                                $where2['voltage_input_end']=['eq',0];
                                $where[]=[$where1,$where2,'_logic'=>'or'];
                            }else{
                                $where['voltage_input_end']=[
                                    ['eq',$request['voltage_input'][0]*1000]
                                ];

                            }
                        }


                    }
                }

                if($typeRes['voltage_output']){
                    if($typeRes['voltage_output_type']==1){
                        //体积
                        if($request['voltage_output']){
                            $where[]=[
                                'voltage_output_start'=>['IN',$request['voltage_output']],
                            ];
                        }
                    }else{
                        //输入电压范围
                        if($request['voltage_output']!=''&&$request['voltage_output']!=','){
                            $request['voltage_output']=explode(',',$request['voltage_output']);
                            if($request['voltage_output'][1]){
                                if(!$request['voltage_output'][0]){
                                    $request['voltage_output'][0]=0;
                                }
                                sort($request['voltage_output']);
                                $where1['voltage_output_start']=['elt',$request['voltage_output'][0]*1000];
                                $where1['voltage_output_end']=[
                                    ['egt',$request['voltage_output'][1]*1000],
                                ];
                                $where2['voltage_output_start']=['between',[$request['voltage_output'][0]*1000,$request['voltage_output'][1]*1000]];
                                $where2['voltage_output_end']=['eq',0];
                                $where[]=[$where1,$where2,'_logic'=>'or'];
                            }else{
                                $where['voltage_output_start']=[
                                    ['eq',$request['voltage_output'][0]*1000]
                                ];

                            }
                        }


                    }
                }

                if($typeRes['volume']){
                    if($typeRes['volume_type']==1){
                        //体积
                        if($request['volume']){
                            $where[]=[
                                'volume_length'=>['IN',$request['volume']],
                            ];
                        }
                    }else{
                        //输入电压范围
                        if($request['volume']!=''&&$request['volume']!=','){
                            $request['output']=explode(',',$request['volume']);
                            if($request['volume'][1]){
                                if(!$request['volume'][0]){
                                    $request['volume'][0]=0;
                                }
                                sort($request['volume']);
                                $where1['volume_length']=['elt',$request['volume'][0]*1000];
                                $where1['volume_width']=[
                                    ['egt',$request['volume'][1]*1000],
                                ];
                                $where2['volume_length']=['between',[$request['volume'][0]*1000,$request['volume'][1]*1000]];
                                $where2['volume_width']=['eq',0];
                                $where[]=[$where1,$where2,'_logic'=>'or'];
                            }else{
                                $where['volume_length']=[
                                    ['eq',$request['volume'][0]*1000]
                                ];

                            }
                        }


                    }
                }
                if($typeRes['custom']){
                    if($typeRes['custom_type']==1){
                        //体积
                        if($request['custom']){
                            $where[]=[
                                'custom_start'=>['IN',$request['custom']],
                            ];
                        }
                    }else{
                        //输入电压范围
                        if($request['custom']!=''&&$request['custom']!=','){
                            $request['custom']=explode(',',$request['custom']);
                            if($request['custom'][1]){
                                if(!$request['custom'][0]){
                                    $request['custom'][0]=0;
                                }
                                sort($request['custom']);
                                $where1['custom_start']=['elt',$request['custom'][0]*1000];
                                $where1['custom_end']=[
                                    ['egt',$request['custom'][1]*1000],
                                ];

                                $where2['custom_start']=['between',[$request['custom'][0]*1000,$request['custom'][1]*1000]];
                                $where2['custom_end']=['eq',0];
                                $where[]=[$where1,$where2,'_logic'=>'or'];
                            }else{
                                $where['custom_start']=[
                                    ['eq',$request['custom'][0]*1000]
                                ];

                            }
                        }


                    }
                }
                if($typeRes['custom1']){
                    if($typeRes['custom1_type']==1){
                        //体积
                        if($request['custom1']){
                            $where[]=[
                                'custom1_start'=>['IN',$request['custom1']],
                            ];
                        }
                    }else{
                        //输入电压范围
                        if($request['custom1']!=''&&$request['custom1']!=','){
                            $request['custom1']=explode(',',$request['custom1']);
                            if($request['custom1'][1]){
                                if(!$request['custom1'][0]){
                                    $request['custom1'][0]=0;
                                }
                                sort($request['custom1']);
                                $where1['custom1_start']=['elt',$request['custom1'][0]*1000];
                                $where1['custom1_end']=[
                                    ['egt',$request['custom1'][1]*1000],
                                ];

                                $where2['custom1_start']=['between',[$request['custom1'][0]*1000,$request['custom1'][1]*1000]];
                                $where2['custom1_end']=['eq',0];
                                $where[]=[$where1,$where2,'_logic'=>'or'];
                            }else{
                                $where['custom1_start']=[
                                    ['eq',$request['custom1'][0]*1000]
                                ];

                            }
                        }


                    }
                }
                if($typeRes['custom2']){
                    if($typeRes['custom2_type']==1){
                        //体积
                        if($request['custom2']){
                            $where[]=[
                                'custom2_start'=>['IN',$request['custom2']],
                            ];
                        }
                    }else{
                        //输入电压范围
                        if($request['custom2']!=''&&$request['custom2']!=','){
                            $request['custom2']=explode(',',$request['custom2']);
                            if($request['custom2'][1]){
                                if(!$request['custom2'][0]){
                                    $request['custom2'][0]=0;
                                }
                                sort($request['custom2']);
                                $where1['custom2_start']=['elt',$request['custom2'][0]*1000];
                                $where1['custom2_end']=[
                                    ['egt',$request['custom2'][1]*1000],
                                ];

                                $where2['custom2_start']=['between',[$request['custom2'][0]*1000,$request['custom2'][1]*1000]];
                                $where2['custom2_end']=['eq',0];
                                $where[]=[$where1,$where2,'_logic'=>'or'];
                            }else{
                                $where['custom2_start']=[
                                    ['eq',$request['custom2'][0]*1000]
                                ];

                            }
                        }


                    }
                }





            }


        }

//
//
//        //输入电压范围
//
//        if($request['input']!=''&&$request['input']!=','){
//            $request['input']=explode(',',$request['input']);
//            if($request['input'][1]){
//                if(!$request['input'][0]){
//                    $request['input'][0]=0;
//                }
//                sort($request['input']);
//                $where['voltage_input_start']=['elt',$request['input'][0]*1000];
//                $where['voltage_input_end']=[
//                    ['egt',$request['input'][1]*1000],
//                    ['eq',0],
//                    'or'
//                ];
//            }else{
//                $where['voltage_input_end']=[
//                    ['eq',$request['input'][0]*1000]
//                ];
//
//            }
//        }
//        //输入电压范围
//        if($request['output']!=''&&$request['output']!=','){
//            $request['output']=explode(',',$request['output']);
//            if($request['output'][1]){
//                if(!$request['output'][0]){
//                    $request['output'][0]=0;
//                }
//                sort($request['output']);
//                $where['voltage_output_start']=['elt',$request['output'][0]*1000];
//                $where['voltage_output_end']=[
//                    ['egt',$request['output'][1]*1000],
//                    ['eq',0],
//                    'or'
//                ];
//            }else{
//                $where['voltage_output_start']=[
//                    ['eq',$request['output'][0]*1000]
//                ];
//
//            }
//        }
//        //体积
//        if($request['volume_length']){
//            $where[]=[
//                'dpa.volume_length'=>['IN',$request['volume_length']],
//            ];
//        }

		if (in_array($request['search_type'],['hot_brand','hot_function'])){

		    if($request['search_type']=='hot_brand' && $request['search']){//品牌名的模糊搜索
                $brandName=M('brand')->field('id')->where(['brand_name'=>['like',"%$request[search]%"]])->select();
                if($brandName){
                    $brandId_arr=[];
                    foreach($brandName as $k=>$v){
                        $brandId_arr[]=$v['id'];
                    }
                    $where[]['brand_id']=['in',$brandId_arr];
                }else{
                    $where[]['brand_id']=0;
                }
            }else if($request['search_type']=='hot_function'){//功能搜索---分类，功能简要，产品描述

				//基本搜索条件
				if($request['search']){
					$sea='%'.str_replace(' ','%',$request['search']).'%';
					$where[]=[
						'parameter'=>['like',$sea],
						'describe'=>['like',$sea],
						'_logic'=>'or'
					];
				}

            }
        }else{

            //if ( $request['brand_id'] ) $where[ 'brand_id' ] = $request['brand_id'] ;//品牌搜素
            //if ( $request['cate_id'] ) {//分类搜索
              //  $cate_id_arr = $this->bottomLevelCategory( $request['cate_id'] );
                //$where[][ 'cate_id' ] = [ 'in', $cate_id_arr ];
            //}

            //关键字搜索
            if ( $request['search'] ){
                if(session('adminId')){//只有管理员可以搜索erp型号
                    $where[]=[
                        'fitemno_access'=>[ 'like', '%' . $request['search'] . '%' ],
                        'fitemno'=>[ 'like', '%' . $request['search'] . '%' ],
                        'p_sign'=>[ 'like', '%' . $request['search'] . '%' ],
                        'p_sign in (select p_sign from dx_product_fitemno where fitemno like "%'.$request['search'].'%")',
                        '_logic'=>'or'
                    ];
                }else{
                    $where[]=[
                        'fitemno_access'=>[ 'like', '%' . $request['search'] . '%' ],
                        'p_sign'=>[ 'like', '%' . $request['search'] . '%' ],
                        '_logic'=>'or'
                    ];
                }
                $this->addUserSearchWordsLog($request['search']);
            }
            if ( $request['search_inner'] ){
                $where[]=[
                    'fitemno_access'=>[ 'like', '%' . $request['search_inner'] . '%' ],
                    'fitemno'=>[ 'like', '%' . $request['search_inner'] . '%' ],
                    'p_sign'=>[ 'like', '%' . $request['search_inner'] . '%' ],
                    '_logic'=>'or'
                ];
                $this->addUserSearchWordsLog($request['search_inner']);
            }

            if ( $request[ 'store' ] ){//库存
                $list=$this->erpProductList(['store'=>['gt',0]]);
                if($list['error']==0){
                    $fitemno_arr=[];
                    foreach($list['data']['list'] as $k=>$v){ $fitemno_arr[]=$v['fitemno']; }
                }
                $where['fitemno']=['in',$fitemno_arr];
            }

            if( $request[ 'productId_arr' ] ) $where['id']=['in',$request[ 'productId_arr' ]]; //多个商品信息获取
        }


        if(isset($request['searchTop'])&&$request['searchTop']){//头条推荐搜索
            $where['search_top']=$request['searchTop'];
        }
        //排序
        if ( $request[ 'sell_sort' ]==12 ) $sort = 'sell_num asc,is_search_top desc';//销量
        else if ( $request[ 'sell_sort' ]==21 ) $sort = 'sell_num desc,is_search_top desc';//销量
        else if ( $request[ 'store_sort' ] == 12 ) $sort = 'ep.store asc,is_search_top desc';//库存
        else if ( $request[ 'store_sort' ] == 21 ) $sort = 'ep.store desc,is_search_top desc';//库存
        else if ( $request[ 'price' ] == 12 ) $sort = 'unit_price asc,is_search_top desc';//价格
        else if ( $request[ 'price' ] == 21 ) $sort = 'unit_price desc,is_search_top desc';//价格

        $page=$request['page']?$request['page']:1;
        $pageSize=$request['pageSize']?$request['pageSize']:C('PAGE_PAGESIZE');

        $product_count=D('product')->productAttrCount($where);//搜索导航栏统计
        $this->assign('product_count',$product_count['data']);

        $whereId_where=["p.is_online"=>1];
        if($where)$whereId_where=[$where,$whereId_where];
        $totalRows=M('product')->alias('p')->where($whereId_where)->count();

        //头条推荐
        $searchTop_where=$whereId_where;
        $searchTop_where['p.is_search_top']=1;
        $searchTop_where['p.search_top']=['neq',''];
        $searchTop=M('product')->field('p_sign,search_top')->alias('p')->where($searchTop_where)->select();
        $searchTopData=[];
        if($searchTop){
            foreach($searchTop as $k=>$v){
                if($v['search_top']){
                    if(!in_array($v['search_top'],$searchTopData['search_top']))
                    $searchTopData['search_top'][]=$v['search_top'];
                }else{
                    $searchTopData['p_sign'][]=$v['p_sign'];
                }
            }
        }
        $this->assign('searchTopData',$searchTopData);

        if($request[ 'price' ]){//价格排序
            $whereId=M('product')->alias('p')->field('p.id,pp.line,pp.unit_price')
                ->join('(select p_id,unit_price,line from (select max(line) as line,p_id,unit_price from dx_product_price group by p_id) as pp_) as pp on pp.p_id=p.id')
                ->where($whereId_where)->order($sort)
                ->limit(($page-1)*$pageSize,$pageSize)->select();

        }else if($request['store_sort']){//库存排序
            $whereId=M('product')->alias('p')->field('p.id,ep.store')
                ->join('left join erp_product as ep on ep.fitemno=p.fitemno')
                ->where($whereId_where)->order($sort)
                ->limit(($page-1)*$pageSize,$pageSize)->select();
        }

        if($request['price']||$request['store_sort']){
            $whereId_index=[];
            if($whereId){
                foreach($whereId as $k=>$v){
                    $whereId_index[]=$v['id'];
                }
                $where=['dp.id'=>['in',$whereId_index]];
            }else{
                $where=['dp.id'=>0];
            }
            $page=0;
        }

        $sort=$request[ 'sell_sort' ]?$sort:'is_search_top desc';
		//$list=$this->productList($where,$page,$pageSize,true,$sort);
//        if($request['search_type']=='hot_function'){
//			$list=$this->productHotList($where,$page,$pageSize,true,$sort);
//		}else{
//			$list=$this->productList($where,$page,$pageSize,true,$sort);
//		}
        $list=$this->productHotList($where,$page,$pageSize,true,$sort);
        $totalRows=$list['data']['count']['count'];
//        echo  "<pre>";
//        print_r($list);
        if($list['error']==0){
            if(!session('adminId')){//只有管理员可以搜索erp型号
                $this->searchHistory->saveSearch($request,$list['data']['list']);//保存搜索历史
            }
            $price_arr=$store_arr=[];
            foreach($list['data']['list'] as $k=>$v){
                $price_arr[]=(float)$v['price'];
                $store_arr[]=(int)$v['store'];
            }
            if($request['price']){
                $is_sort=((int)$request[ 'price' ] === 12)?SORT_ASC:SORT_DESC;
                array_multisort($price_arr,$is_sort,$list['data']['list']);
            }else if($request['store_sort']){
                $is_sort=((int)$request[ 'store_sort' ] === 12)?SORT_ASC:SORT_DESC;
                array_multisort($store_arr,$is_sort,$list['data']['list']);
            }
            $adminList=M('user','sys_')->field('nickname,qq,wechat,mobile,product_category')->where(['is_customer_service'=>1])->select();
            foreach($list['data']['list'] as $k=>$v){//客服服务的产品的类
                foreach($adminList as $k2=>$v2){
                    if(strpos($v2['product_category'],",$v[cate_id],")!==false){
                        $list['data']['list'][$k]['customer_service'][]=$v2;
                    }
                }
            }
        }

        if(IS_AJAX) return $list;
        $request=I( 'post.' );
        if($request['cate_id']){
            $request=array_merge($request,M('category')->field("cate_name")->where(['id'=>$request['cate_id']])->find());
        };
        $request['pageSize']=$pageSize;
		$this->assign( 'request', $request );
		$this->assign( 'search_data', $list['data']['list'] );// 赋值数据集

		$Page = new \Think\Page( $totalRows, $pageSize );// 实例化分页类 传入总记录数和每页显示的记录数
		$Page->setConfig( 'prev', '<上一页' );
		$Page->setConfig( 'next', '下一页>' );
		if($totalRows>$pageSize)$show = $Page->show();// 分页显示输出
		$this->assign( 'page', $show );// 赋值分页输出
        $this->assign( 'count',$totalRows );// 总记录数
		$this->assign( 'p_num', ceil( $totalRows / $pageSize ) );// 总记录数
		$this->display();
	}

	/*
	 *  分类的所有子类
	 */
	public function all_son_category( $cate_id = 1 )
	{
		$category = D( 'category' )->where( [ 'id' => $cate_id ] )->find();
		$lft = $category[ 'lft' ];
		$rht = $category[ 'rht' ];
		$all_son_category = D( 'category' )->where( [ 'usable' => 1, [ 'lft' => [ 'between', [ $lft, $rht ] ] ], [ 'rht' => [ 'between', [ $lft, $rht ] ] ] ] )->select();
		
		return $all_son_category;
	}
	
	/*
	 *  分类的最底层子类
	 */
	public function bottomLevelCategory( $cate_id = 1 )
	{
		$all_son_category = $this->all_son_category( $cate_id );
		$level_last = [];
		foreach ( $all_son_category as $k => $v ) {
			if ( ( $v[ 'lft' ] + 1 ) == $v[ 'rht' ] ) {//最底层分类
				$level_last[] = $v[ 'id' ];
			}
		}
		
		return $level_last;
	}
	
	/*
	 *
	 *  根据pid得产品数据
	 * @return array
	 */
	public function productBaseData( $field_pid )
	{
		$pid_str = '';
		foreach ( $field_pid as $k => $v ) {
			$pid_str .= $v[ 'id' ] . ',';
		}
		$pid_str = substr( $pid_str, 0, -1 );
		$product_list = [];
		if ( $field_pid ) {
			//产品结果列表
			$product = D( 'product' );
			$product_list = $product->field( 'dx_product.*,dx_product_detail.img,dx_product_detail.pdf,dx_brand.brand_name,dx_product_detail.describe' )->join( 'left join dx_product_detail on dx_product_detail.p_id=dx_product.id' )->join( 'left join dx_brand on dx_brand.id=dx_product.brand_id' )->where( "dx_product.id in (" . $pid_str . ")" )->select();
			$order=new OrderController();
			$product_result = [];
			foreach ( $product_list as $k => $v ) {
				$v[ 'price_section' ] = $order->productSectionNumPrice($v['id']);
				$v[ 'price_sort' ] = $v[ 'price' ];
				$categoryParentPath = $this->categoryParentPath( $v[ 'cate_id' ] );
				$v[ 'cate_name_level1' ] = $categoryParentPath;
				$product_result[ $k ] = $v;
			}
		}
		return $product_result;
	}
	
	/*
	 *
	 *  取出上一级父类名称
	 * @return array
	 */
	public function categoryParentPath( $id )
	{
		$category = D( 'category' )->where( ['id'=>$id] )->find();
		$lft_category=D( 'category' )->where( ['lft'=>['lt',$category['lft']],'rht'=>['gt',$category['rht']]] )->order('lft asc')->select();
		$upper_lever=$lft_category['1'];
		return $upper_lever[ 'cate_name' ];
	}
	
	/*
	 *
	 *  取出所有分类
	 * @return array
	 */
	public function categoryList()
	{
		if ( $this->category_list ) return $this->category_list;
		$result = [];
		$category = D( 'category' );
		$category_list = $category->select();
		foreach ( $category_list as $k => $v ) {
			$result[ $v[ 'id' ] ] = $v;
		}
		$this->category_list = $result;
		
		return $result;
	}
	
	/*
	 *
	 *  取出所有品牌
	 * @return array
	 */
	public function brandList()
	{
		if ( $this->brand_list ) return $this->brand_list;
		$result = [];
		$brand = D( 'brand' );
		$brand_list = $brand->select();
		foreach ( $brand_list as $k => $v ) {
			$result[ $v[ 'id' ] ] = $v;
		}
		$this->brand_list = $result;
		
		return $result;
	}
	
	/*
	 * 
	 *  搜索引擎,返回搜索内容
	 * @return array
	 */
	public function xunsearchOut( $query, $searchDb = 'product' )
	{
		$xs = new \XS( $searchDb ); // 建立 XS 对象，项目名称为：demo
		$search = $xs->search; // 获取 搜索对象
		$search->setQuery( $query ); // 设置搜索语句
		$docs = $search->search(); // 执行搜索，将搜索结果文档保存在 $docs 数组中
		$count = $search->count(); // 获取搜索结果的匹配总数估算值
		
		return [ 'data' => $docs, 'count' => $count ];
	}
	
	
	public function curl__( $url )
	{
		//初始化
		$ch = curl_init();
		curl_setopt( $ch, CURLOPT_URL, $url );
		curl_setopt( $ch, CURLOPT_RETURNTRANSFER, 1 );
		curl_setopt( $ch, CURLOPT_HEADER, 0 );
		//执行并获取HTML文档内容
		$output = curl_exec( $ch );
		//释放curl句柄
		curl_close( $ch );
		
		return $output;
	}
	
	
	/*
	 * 用户商品详情页 - 分享
	 *
	 */
	public function share()
	{
		$type = strtolower( I( 'type' ) );
		if ( empty( $type ) ) {
			return false;
			exit();
		}
		$class = $type . 'Share';
		//获取当前登录用户open信息
		if ( !is_login() ) redirect( U( 'Home/Account/login' ) );
		$openInfo = session( 'userInfo.open' );
		//当前分享方式的openid
		$open_id = $openInfo[ $type ][ 'open_id' ];
		$status = $openInfo[ $type ][ 'status' ];
		if ( $status != 0 ) {
			$this->error( '当前系统端口已关闭!请稍后再试', U( 'Home/Default/index' ) );
		}
		//执行分享方法
		$this->$class();
	}
	
	/*
	 * 新浪微博分享
	 *
	 */
	protected function sinaShare()
	{
		$open = S( $this->ssid . 'open' );
		$token = $open[ 'sina' ];
		//若不存在token
		if ( empty( $token ) ) {
			//TODO  跳转新浪微博账号绑定
			if ( IS_AJAX ) {
				$this->ajaxReturnStatus( 1002, '您的新浪账号未绑定' );
			} else {
				return [];
			}
		}
		$status = I( 'status' );
		if ( mb_strlen( I( 'status' ) ) > 140 ) {
			$this->error( '分享文字不能超过140个字符', '', 3 );
		}
		$url = I( 'url' );
		$img = SITE_PATH . ltrim( I( 'pic' ), '/' );
		$aKey = C( 'THINK_SDK_SINA.APP_KEY' );
		$sKey = C( 'THINK_SDK_SINA.APP_SECRET' );
		$access_token = $token[ 'access_token' ];
		$c = new sinaClient( $aKey, $sKey, $access_token );
		$data = $c->share( $status . $url, $img );
		if ( $data[ 'id' ] != 0 && $data[ 'mid' ] == $data[ 'idstr' ] ) {
			if ( IS_AJAX ) {
				$this->ajaxReturnStatus( 1001, '分享成功' );
			} else {
				return true;
			}
		} else {
			if ( IS_AJAX ) {
				$this->ajaxReturnStatus( 1002, '分享失败' );
			} else {
				return false;
			}
		}
	}
	
	
	/*
	 * 腾讯微博分享
	 *
	 */
	protected function tencentShare()
	{
		$open = S( $this->ssid . 'open' );
		$token = $open[ 'qq' ];
		$qq = ThinkOauth::getInstance( 'qq', $token );
		$param[ 'content' ] = I( 'status' ) . I( 'url' );
		$param[ 'pic' ] = '@' . SITE_PATH . ltrim( I( 'pic' ), '/' );
		$data = $qq->call( 't/add_pic_t', $param, 'POST', true );
		if ( $data[ 'ret' ] == 0 && $data[ 'msg' ] == 'ok' ) {
			if ( IS_AJAX ) {
				$this->ajaxReturnStatus( 1001, '分享成功' );
			} else {
				return true;
			}
		} else {
			if ( IS_AJAX ) {
				$this->ajaxReturnStatus( 1002, '分享失败' . $data[ 'msg' ] );
			} else {
				return false;
			}
		}
	}
	
	/*
	 * 添加商品到收藏夹
	 */
	public function addCollect()
	{
		//添加到收藏夹的商品id
		$id = I( 'p_id' );
		empty( $id ) && $this->ajaxReturnStatus( 1001, '数据id不能为空' );
		$more = false;
		$max = 50; //收藏夹最大数
		$user_id = session( 'userId' );
		if ( is_array( $id ) ) {
			$more = true;
		}
		$collDB = M( 'user_collect' );
		$data = $collDB->field( 'collect' )->where( [ 'user_id' => $user_id ] )->find();
		//数据不存在
		if ( empty( $data ) ) {
			$add[ 'user_id' ] = $user_id;
			if( $more ){
				$add[ 'collect' ] = json_encode( $id );
			}else{
				$data[] = $id;
				$add[ 'collect' ] = json_encode($data);
			}
			
			$re = $collDB->add( $add );
			if ( $re ) {
				$this->ajaxReturnStatus( 0000, '添加到收藏夹成功' );
			} else {
				$this->ajaxReturnStatus( 1002, '添加到收藏夹失败' );
			}
		} else {
			//多个
			if ( $more ) {
				$num = count( $id );
				$n = 0;
				$collect = json_decode( $data[ 'collect' ] );
				foreach ( $id as $k => $item ) {
					
					$count = count( $collect );
					//数量超过 那么弹出最后一个商品id;
					if ( $count >= $max ) {
						array_pop( $collect );
					}
					//dump($item);
					//如果已存在该商品 那么将这个商品调整排列第一位
					$key = array_search( $item, $collect );
					if ( $key >= 0 && $key !== false ) {
						unset( $collect[ $key ] );
					}
					//dump($collect);
					//入栈
					array_unshift( $collect, $item );
					$n++;
				}
				$save = json_encode( $collect );
				$collDB->startTrans();
				$re = $collDB->where( [ 'user_id' => $user_id ] )->save( [ 'collect' => $save ] );
				if ( $n == $num ) {
					$collDB->commit();
					$this->ajaxReturnStatus( 0000, '添加到收藏夹成功' );
				} else {
					$collDB->rollback();
					$this->ajaxReturnStatus( 1003, '添加到收藏夹失败' );
				}
			} else {
				$collect = json_decode( $data[ 'collect' ],true );
				$count = count( $collect );
				//数量超过 那么弹出最后一个商品id;
				if ( $count > $max ) {
					array_pop( $collect );
				}
				//dump($collect);
				//如果已存在该商品 那么将这个商品调整系列第一位
				$key = array_search( $id, $collect );
				if ( $key >= 0 && $key !== false ) {
					unset( $collect[ $key ] );
				}
				//入栈
				array_unshift( $collect, $id );
				$save = json_encode( $collect );
				$re = $collDB->where( [ 'user_id' => $user_id ] )->save( [ 'collect' => $save ] );
				if ( $re !== false ) {
					$this->ajaxReturnStatus( 0000, '添加到收藏夹成功' );
				} else {
					$this->ajaxReturnStatus( 1004, '添加到收藏夹失败' );
				}
			}
		}
	}
	
	
	/*
	 * 根据cate_id 获取分类名称
	 *
	 */
	public function ajaxGetCategoryName()
	{
		$id = I('cate_id');
		empty($id) && $this->ajaxReturnStatus(1001,'id错误');
		$res = M('category')->field('cate_name')->where(['id'=>$id])->find();
		$this->ajaxReturnStatus(0,$res['cate_name']);
	}
	
	
	/*
	 *
	 * 记录用户搜索关键词
	 *
	 */
	public function addUserSearchWordsLog($words='')
	{
		if( empty($words) ) return true;
		$user_id = session('userId')?session('userId'):0;
		$user_name = session('userInfo.user_name')?session('userInfo.user_name'):'游客';
		$time = date('Y-m-d H:i:s', time());
		$str = '##'.$time."||".$user_id."||".$user_name."||".$words.PHP_EOL;
		$logDir = MYLOG_PATH.'UserSearch/';
		if( !file_exists($logDir) ) mkdir( $logDir, 0755, true );
		$logNum = file_get_contents($logDir.'UserSearchLog.txt');
		if( !$logNum ){
			$logNum = 1;
		}
		//当前日志文件名
		$logFileName = $logDir.'log'. sprintf( '%08s', $logNum).'.txt';
		//若文件超过1M 那么就新建文件记录
		if( filesize($logFileName) >= 1048567 ){
			$logNum +=1;
			$logFileName = $logDir.'log'. sprintf( '%08s', $logNum).'.txt';
		}
		file_put_contents($logFileName,$str,FILE_APPEND);
	}

    /**
     * @desc 议价的报备信息添加
     */
    public function productReport(){
        if(IS_AJAX){
            $request=I('post.');
            $result=D('product')->productReport($request);
            if( $result['error'] === 0 ){
                MsgController::writeMsgToUserSale( session('userId'), '有新报备信息!', '报备id:'.$result['data'] );
                unset( $result['data'] );
            }
            die(json_encode($result));
        }
        $get=I('get.');
        $where=[];
        if(isset($get['p_id'])&&$get['p_id']) $where['id']=$get['p_id'];
        $list=$this->productList($where);
        if($list['error']==0){
            $adminList=M('user','sys_')->field('nickname,qq,wechat,mobile,product_category')->where(['is_customer_service'=>1])->select();
            foreach($list['data']['list'] as $k=>$v){//客服服务的产品的类
                foreach($adminList as $k2=>$v2){
                    if(strpos($v2['product_category'],",$v[cate_id],")!==false){
                        $list['data']['list'][$k]['customer_service'][]=$v2;
                    }
                }
            }
        }

        $this->assign('product',$list['data']['list'][0]);
        $this->display();
    }
    /**
     * @desc banner详情
     */
    public function bannerDetail(){

        $get=I('get.');
        $this->assign('request',$get);
        $this->display('Default/bannerDetail');
    }


    public function bannerDetail_text(){

        $get=I('get.');
        $textInfo=M("advert_text")->where(['id'=>$get['banner']])->find();
        $textInfo['text']=htmlspecialchars_decode($textInfo['text']);
        $texts=M("advert_text")->field("text_titile,update_time")->where("status=1")->order("sort desc")->select();
        $this->assign('textInfo',$textInfo);
        $this->assign('texts',$texts);
        $this->display('Default/bannerDetail_text');
    }





}
